name: my_home
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --------------------------------------------------
  # ðŸŒ¿ Core Flutter & UI Packages
  # --------------------------------------------------
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3 # Responsive sizing
  flutter_svg: ^2.2.1 # SVG image rendering
  lottie: ^3.3.2 # Animations
  skeletonizer: ^2.1.0+1 # Loading skeletons
  toastification: ^3.0.3 # Toast notifications
  flutter_slidable: ^4.0.3 # Swipeable list tiles

  # --------------------------------------------------
  # âš™ï¸ State Management & Dependency Injection
  # --------------------------------------------------
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0 # Service locator pattern

  # --------------------------------------------------
  # ðŸ§­ Navigation & Routing
  # --------------------------------------------------
  go_router: ^16.2.4

  # --------------------------------------------------
  # ðŸŒ Networking & APIs
  # --------------------------------------------------
  dio: ^5.9.0 # HTTP client
  retrofit: ^4.8.0 # Code generator for REST APIs
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0  # For model annotations


  # --------------------------------------------------
  # ðŸ’¾ Local Storage & Caching
  # --------------------------------------------------
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1 # Image caching

  # --------------------------------------------------
  # ðŸ§  Functional & Utility Packages
  # --------------------------------------------------
  dartz: ^0.10.1 # Functional programming tools (Either, Option)
  intl: ^0.20.2 # Internationalization & date formatting
  url_launcher: ^6.3.2 # Open links and apps

  # --------------------------------------------------
  # â˜ï¸ Backend & Auth Services
  # --------------------------------------------------
  supabase_flutter: ^2.10.3

  # --------------------------------------------------
  # ðŸ’« Animations
  # --------------------------------------------------
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^1.3.1 # Preview app on multiple devices


  # --------------------------------------------------
  # ðŸ§¹ Code Quality & Linting
  # --------------------------------------------------
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
